import { Probot } from "probot";

export = (app: Probot) => {
  app.on("pull_request.opened", async (context) => {
    const pr = context.payload.pull_request;
    const repo = context.repo();

    // 获取 PR 的 diff
    const diffResponse = await context.octokit.pulls.get({
      ...repo,
      pull_number: pr.number,
      headers: {
        accept: "application/vnd.github.v3.diff",
      },
    });

    const diff = diffResponse.data as unknown as string;

    // 分析 diff
    const { aiLines, totalLines } = analyzeDiff(diff);

    if (totalLines === 0) {
      await context.octokit.issues.createComment({
        ...repo,
        issue_number: pr.number,
        body: "ℹ️ 本次 PR 没有新增代码行，无法分析 AI 辅助率。",
      });
      return;
    }

    const aiRatio = ((aiLines / totalLines) * 100).toFixed(1);
    const confidence = aiLines > 0 ? "高" : "中";

    let emoji = "🟡";
    if (parseFloat(aiRatio) > 70) emoji = "🟢";
    else if (parseFloat(aiRatio) > 30) emoji = "🟡";
    else emoji = "⚪";

    const commentBody = `${emoji} **AI 辅助率 ${aiRatio}%** · 人类策展率 ${(100 - parseFloat(aiRatio)).toFixed(1)}%
    
> 检测置信度: ${confidence}
> AI 生成代码行数: ${aiLines} / 总新增行数: ${totalLines}
>
> *本分析由 Trace 自动生成，基于 Copilot 元数据检测。如有误判，欢迎反馈。*`;

    await context.octokit.issues.createComment({
      ...repo,
      issue_number: pr.number,
      body: commentBody,
    });
  });
};

function analyzeDiff(diff: string): { aiLines: number; totalLines: number } {
  const lines = diff.split("\n");
  let aiLines = 0;
  let totalAddedLines = 0;

  for (const line of lines) {
    // 只统计新增的行（以 + 开头，但不是 +++ 文件头）
    if (line.startsWith("+") && !line.startsWith("+++")) {
      totalAddedLines++;

      // 检测 Copilot 留下的标记
      if (
        line.includes("Generated by Copilot") ||
        line.includes("copilot-suggestion") ||
        line.includes("@copilot") ||
        line.includes("GitHub Copilot")
      ) {
        aiLines++;
      }
    }
  }

  return { aiLines, totalLines: totalAddedLines };
}